### ISSUE TITLE
Selecteur de vendor bower

### ISSUE THREAD

**Issue by bbrochier** [c2is/c2is-onetea#11]
Un page avec des cases à coché des vendors que l'on veut inclure.
A la validation, cela genere une commande bower a copy/past dans le terminal... ou un fichier bash a executer?

---
#### Todo
- [ ] Lister les vendors qu'on utilise souvent à intégrer
- [ ] Définir le fonctionnement précis désiré
- [ ] Se mettre d'accord sur wireframe
- [ ] Poser la page et fonctionnement

---
#### Liste de suggestion
- jquery
- modernizr
- normilize css
- jquery ui
- modernizr
##### popin
- colorbox
- bPopup
##### skin select
- select2
- chosen
- selectboxit
##### carousel
- owl carousel
- slick slider
##### infobox
- hint css
##### range slider
- no ui slider
##### images
- imagesLoaded
##### responsive
- Both
- device.js
##### animation
- trans
- velocity
##### data
- Bring
##### scroll
- GoTo
##### accordion
- Fold

---
##
